# overrides for local development, not used in CI
version: '3'
services:
  pandoc-lambda:
    volumes:
      - ./docker/pandoc-lambda/function/:/function
    build:
      context: ./docker/pandoc-lambda
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-pandoc-lambda:0.64-776ceab36509fa43d4c505e6e3c84252
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - .
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-python:0.89-2fdbe9b2ccd89395b0e1d96da05940de
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
    environment:
      - CAPAPI_API_KEY
      - GPO_API_KEY
      - MATOMO_API_KEY
      - MATOMO_SITE_URL
