# overrides for local development, not used in CI
services:
  pandoc-lambda:
    volumes:
      - ./docker/pandoc-lambda/function/:/function
    build:
      context: ./docker/pandoc-lambda
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-pandoc-lambda:0.65-76db60c3f9cd9d36efc2785f49f139ba
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - .
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-python:0.114-9f1e6b81ca58b4ba3d70b870fc1380e6
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
    environment:
      - CAPAPI_API_KEY
      - GPO_API_KEY
      - COURTLISTENER_API_KEY      
      - MATOMO_API_KEY
      - MATOMO_SITE_URL
