# overrides for local development, not used in CI
services:
  pandoc-lambda:
    volumes:
      - ./docker/pandoc-lambda/function/:/function
    build:
      context: ./docker/pandoc-lambda
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-pandoc-lambda:0.66-f4ef497565cd325e6161cb6b0dafe814
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - .
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/h2o-python:0.115-f70184667afdf54dacb61f46f296565d
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - web/requirements.txt
    environment:
      - CAPAPI_API_KEY
      - GPO_API_KEY
      - COURTLISTENER_API_KEY      
      - MATOMO_API_KEY
      - MATOMO_SITE_URL
