name: MyPy

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
        python-version: '3.9'
      - run: pip install mypy
      - run: mypy web # Config is in main/setup.cfg
